- f3

  - 回答: C が表示された後、Aが表示され、その後発生したエラーXはキャッチされない。
  - 理由: waitは非同期なので直ちにfinallyが実行され、その後非同期処理のAが表示される。thenのコールバック内の例外はtry-catchではキャッチされない。

- f4

  - 回答:2秒後にAが表示され、その1秒後にBが表示され、最後に100が表示される。
  - 理由:wait2の完了を待った後、logA()が実行され40が返される。次のthenの中でPromiseが返されており、1秒後にBが表示され100が返されるため、最後のthenで100が表示される。

- f5

  - 回答:1秒後にBが表示され、その後1秒後にAが表示された後40が返され、最後に40が表示される。
  - 理由:2つめのthenは引数として関数が渡されないため、2秒後にBが返されており、その後1つ目の引数の関数でAが表示されて40が返され、40が3つ目のthenの引数となり、40が表示される。

  ※ 最初にwait2 が動いて、thenの中の引数が評価されてwait1が動いて、wait1が早いので、実行される。その後wait2の方が実行される。

- f6

  - 回答: 1秒後にAが表示されその1秒後にBが表示され、さらにその1秒後にCが表示される。
  - 理由: 1秒後にAが表示され、pが満たされた後、二つのthenが同時呼び出され、1秒後にBが表示され、2秒後にCが表示される。

- f7

  - 回答:　１秒後にAが表示され、2秒後にBが表示され最後にCが表示される。
  - 理由: 1秒後にAが表示され、2秒後にはpは満たされているため、すぐにBが表示されCが表示される。

- f8

  - 回答: 1秒後にXが表示されAが表示される。
  - 理由: エラーが発生し、キャッチされるまで伝搬されXが表示された後、finallyでAが表示される。

- f9

  - 回答:Yが表示されAが表示される。
  - 理由:エラーが発生しキャッチされるため、Yが表示される。

- f10

  - 回答: 1秒後にAが表示された後Yのエラーが発生する。
  - 理由:エラーが発生し、キャッチされないためそのままエラーになる。

- f11

  - 回答:Xが表示される。
  - 理由:エラーはキャッチ可能でXが表示される。

- f12

  - 回答:Xのエラーが発生する。
  - 理由:Promiseないでも、コールバック関数の中でエラーが発生した場合はキャッチされない。
